### ISSUE TITLE
Exception thrown in WishPanel after attempting to save to a wish.

### ISSUE THREAD

**Issue by leongshengmin** [CS2103-AY1819S1-T16-1/main#135]
Exception is thrown when displaying wish history in `WishDetailSavingHistory`. When the save command is performed, the `wishTransaction` object and `WishTransaction.xml` file is updated with the saved amount however, the log shows a `NullPointerException` and nothing is displayed on the savings history panel. 

Below shows the stack trace of the exception thrown:

`Nov 08, 2018 4:38:08 PM seedu.address.commons.core.EventsCenter post
INFO: ------[Event Posted] seedu.address.commons.events.ui.WishDataUpdatedEvent: WishDataUpdatedEvent
Nov 08, 2018 4:38:08 PM seedu.address.ui.WishDetailSavingAmount handleWishDataUpdatedEvent
INFO: ---[Event handled][WishDataUpdatedEvent]
Nov 08, 2018 4:38:08 PM seedu.address.ui.WishDetailSavingHistory handleWishDataUpdatedEvent
INFO: WishHistory updated: ---[Event handled][WishDataUpdatedEvent]
Nov 08, 2018 4:38:08 PM com.google.common.eventbus.EventBus$LoggingHandler handleException
SEVERE: Exception thrown by subscriber method handleWishDataUpdatedEvent(seedu.address.commons.events.ui.WishDataUpdatedEvent) on subscriber seedu.address.ui.WishDetailSavingHistory@4be41471 when dispatching event: WishDataUpdatedEvent
java.lang.NullPointerException
	at seedu.address.ui.WishDetailSavingHistory.loadWishDetails(WishDetailSavingHistory.java:56)
	at seedu.address.ui.WishDetailSavingHistory.handleWishDataUpdatedEvent(WishDetailSavingHistory.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:95)`

**Comment by leongshengmin** [comment]
bug fixed 
see #137
